org: jmeash
app: london-transport
service: london-transport-bot

provider:

  name: aws

  runtime: nodejs10.x

  region: eu-west-1

plugins:
  - serverless-offline

functions:

  ltbot:

    handler: handler.ltbot

    events:

      - http:

          path: ltbot

          method: post

          cors: true
