org: jmeash
app: london-transport
service: london-transport-bot

provider:

  name: aws
  runtime: nodejs12.x
  region: ${env:DYNAMODB_REGION}
  stage: dev
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: ${env:DYNAMODB_ARN}


plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

functions:

  ltbot:
    handler: handler.ltbot
    events:
      - http:
          path: ltbot
          method: post
          cors: true

  cron:
    handler: handler.cron
    events:
      - schedule:
          name: cron-checks-commutes-notifications
          description: 'Checks if a commute should be checked and notified'
          rate: cron(0/5 5-23 ? * MON-FRI *)
