org: jmeash
app: london-transport
service: london-transport-bot

provider:

  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  stage: dev

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline
functions:

  ltbot:

    handler: handler.ltbot

    events:

      - http:

          path: ltbot

          method: post

          cors: true
